apiVersion: networking.k8s.io/v1  
kind: Ingress 
metadata:
  name: spinnaker-ingress
  namespace: spinnaker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
      - spinnaker.panda-labs.online
    secretName: spinnaker-ui-tls
  ingressClassName: nginx
  rules:
    - host: spinnaker.panda-labs.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spin-deck
                port:
                  number: 9000

---

apiVersion: networking.k8s.io/v1  
kind: Ingress 
metadata:
  name: spinnaker-api-ingress
  namespace: spinnaker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
      - spinnaker-api.panda-labs.online
    secretName: spinnaker-api-tls
  ingressClassName: nginx
  rules:
    - host: spinnaker-api.panda-labs.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spin-gate
                port:
                  number: 8084