apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    version: v3
  name: hello-world-replica
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service hello-world-service-prod"]'
spec:
  replicas: 4
  selector:
    matchLabels:
      version: v3
  template:
    metadata:
      labels:
        version: v3
    spec:
      containers:
        - image: 'shubhashish/helloworld:${image_tag}'
          imagePullPolicy: Always
          name: hello-world-app
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-prod
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: hello-world-deployment-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress-prod
spec:
  ingressClassName: nginx
  rules:
    - host: hello.panda-labs.online
      http:
        paths:
          - backend:
              service:
                name: hello-world-service-prod
                port:
                  number: 3000
            path: /
            pathType: Prefix