apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v3
    app: hello-world-deployment-stage
  name: hello-world-deployment-stage
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world-stage
  template:
    metadata:
      labels:
        app: hello-world-stage
    spec:
      containers:
        - image: 'shubhashish/helloworld:${image_tag}'
          imagePullPolicy: Always
          name: hello-world-stage
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-stage
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: hello-world-deployment-stage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress-stage
spec:
  ingressClassName: nginx
  rules:
    - host: hello-stage.panda-labs.online
      http:
        paths:
          - backend:
              service:
                name: hello-world-service-stage
                port:
                  number: 3000
            path: /
            pathType: Prefix
