---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker-user-sa
  namespace: spinnaker

---
apiVersion: v1
kind: Secret
metadata:
  name: spinnaker-user-secret
  namespace: spinnaker
  annotations:
    kubernetes.io/service-account.name: spinnaker-user-sa
type: kubernetes.io/service-account-token